#!/bin/sh

# {bouncer,counter,display}-000.example.net
# ^^^^^^^^^^^^^^^^^^^^^^^^^ = DEVICE
DEVICE=`hostname -f | cut -d- -f1`

if [ -f /etc/default/studio-system ]; then
    . /etc/default/studio-system
fi

# allow override on read-only root systems
if [ -f /var/run/studio-system ]; then
    . /var/run/studio-system
fi

case "${DEVICE}" in
    "bouncer")
        BINARY="/usr/bin/bouncer"
        PARAMETER=""
    ;;
    "counter")
        BINARY="/usr/bin/counter"
        PARAMETER=""
    ;;
    *)
        # display application as default / fallback
        BINARY="/usr/bin/display"
        PARAMETER="${DISPLAY_URL}"

        # disable display power-management
        xset -display :0 -dpms
    ;;
esac

# run program in background and window manager in foreground
${BINARY} ${PARAMETER} &
exec matchbox-window-manager
