#!/bin/sh

# {bouncer,counter,display}-000.example.net
host_prefix=`hostname -f | cut -d- -f1`

case "${host_prefix}" in
    "bouncer")
        binary="/usr/bin/bouncer"
        parameter=""
    ;;
    "counter")
        binary="/usr/bin/counter"
        parameter=""
    ;;
    *)
        # display application as default / fallback
        binary="/usr/bin/display"
        parameter="http://www.shadowhunt.de"

        # disable display power-management
        xset -display :0 -dpms
    ;;
esac

# run program in background and window manager in foreground
${binary} ${parameter} &
exec matchbox-window-manager
